### PR TITLE
converted to android studio gradle project

### PR DESCRIPTION
**Pull request by xuefer**
Signed-off-by: Xuefer <xuefer@gmail.com>

### CODE REVIEW

**Comment by scola** [comment]
I will check this pull request this afternoon, 
did you test on your device?
it works well ?

**Comment by scola** [comment]
@xuefer Thanks for your pull request

**Comment by xuefer** [comment]
it builds withotu error, it runs, except it throw out a toast saying it's i don't have the right key with authorization to use calendar API of google "cloud". the exact words are: "[Error] Access Not Configured. Calendar API has not been used in project 608941808256 before or it is disabled. Enalbe it by visiting https://console.developer.com/apis/api/calendar/overview?project=608941808256 then retry. .........."

**Comment by scola** [comment]
Calendar Provider can be used for those who do not have google play service

**Pull request merged**
